# Site
title: "Haade Alsace domotique"
description: "Home Assistance Alsace domotique et électronique."
name: "Haade"
logo: 'assets/images/logo.webp'
favicon: 'assets/images/favicon.png'
url: https://haade-administrator.github.io
baseurl: /futurofhaade
mailchimp-list: 'https://haade.us4.list-manage.com/subscribe/post?u=86f32891957737a57c0b4ade8&amp;id=92dadba2b4'
permalink: /:title/
email: administrateur@haade.fr

#google
google_site_verification: 'SZHADy8knzo8Q_dv__GBJYH7U10uDTYtWu31EqGqtvQ'

# google analytics + futur pageviews
google_analytics:
  id:  'G-1DEJLWC188'

# Multilang
# https://matthewlincoln.net/2020/03/01/multilingual-jekyll.html // https://www.usecue.com/blog/multilingual-jekyll-websites/ // https://www.kooslooijesteijn.net/blog/multilingual-website-with-jekyll-collections
# gitub project usecue /// https://github.com/jhvanderschee/usecuewebsite /// https://github.com/ranbureand/multilingual-experiment
default_language: 'fr'
fallback_page: 'sorry'

# permalink: /:categories/:title/



# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-figure
  - jekyll-gist
  - jekyll-last-modified-at
  - jekyll-imagemagick

# Set which comment system to use
comments:
  provider: giscus

# You must install giscus github app before use.(https://github.com/apps/giscus)
# Make sure all variables are set properly. Check below link for detail.
# https://giscus.vercel.app/
giscus:
  repo:                "haade-administrator/haade.fr"
  repo-id:             "R_kgDOHHK8ZA"
  category:            "Comments"
  category-id:         "DIC_kwDOHHK8ZM4COugG"
  mapping:             "pathname"
  reaction-enabled:    "1"
  emit-metadata:       "0"
  theme:               "light"
  position:            "top"
  loading:             "lazy"
  lang:                "fr"
  crossorigin:         "anonymous"

# Liste des catégories
collections:
  category:
    output: true # générer la page HTML
    # permalink: /:collection/:name
    # exemple -> /category/informatique/index.html

defaults:
  - scope:
      path: "_posts/fr" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      language: fr
      permalink: fr/blog/:title

  - scope:
      path: "_posts/en" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      language: en
      permalink: en/blog/:title

  - scope:
      path: "_category/fr" # an empty string here means all files in the project
    values:
      layout: "category"
      language: fr
      permalink: fr/:collection/:name


  - scope:
      path: "_category/en" # an empty string here means all files in the project
    values:
      layout: "category"
      language: en
      permalink: en/:collection/:name



# Jekyll paginate v2 Pagination
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true



  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 6

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: 'fr_FR'

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

######################### end jekyll-paginate-v2 ###################################

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Vanilla back to top ("enabled" or "disabled")
backtotop: "enabled"

# Toggle dark / light button ("enabled" or "disabled")
darklight: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Cookie consent ("enabled" or "disabled")
cookie_consent: "enabled"

# countapi.xyz
countapi:
  namespace: haade-administrator.github.io
  key: 4299f32a-3d13-4fe4-91f7-87c847196022

# Sass
sass:
  sass_dir: _sass
  style: compressed

# compress link http://jch.penibelst.de/

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

# jekyll imagemagick

imagemagick:
  enabled: true
  widths:
    - 0
    - 272
    - 368
    - 553
    - 820
    - 944

  input_directories:
    - assets/images/../

  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
  output_formats:
     # jpg: "-quality 85%"
    webp: "-quality 85%"


exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
