# Site
title: "Haade.fr"
description: "Home Assistance Alsace domotique et électronique."
name: "Haade"
logo:
  path: 'logo.png'
  width: 250
  height: 94
  alt: 'Logo officiel du site domotique Haade'
  id: 'logoIImage'
favicon: 'assets/images/favicon.png'
url: https://haade.fr
baseurl: 
mailchimp-list: 'https://haade.us4.list-manage.com/subscribe/post?u=86f32891957737a57c0b4ade8&amp;id=92dadba2b4'
permalink: /:title/
email: administrateur@haade.fr
words_per_minute: 180

#https://formsubmit.co/
formsubmitco: 'db65ec0e1e884cf4b77b96fa7ce5d63e'

#socialnetwork
social:
  discord: 'FaK6MuZ2'
  youtube: 'UCcXJ1ZsjEvQxuWJy7gH-A6w'

# google analytics + futur pageviews
google_analytics:
  id: ''

goatcounter_analytics:
  id: 'haade'

# Multilang
# https://matthewlincoln.net/2020/03/01/multilingual-jekyll.html // https://www.usecue.com/blog/multilingual-jekyll-websites/ // https://www.kooslooijesteijn.net/blog/multilingual-website-with-jekyll-collections
# gitub project usecue /// https://github.com/jhvanderschee/usecuewebsite /// https://github.com/ranbureand/multilingual-experiment
default_locale: 'fr_FR'
fallback_page: 'index'

# permalink: /:categories/:title/



# Plugins
plugins:
  - jekyll-figure
  - jekyll-gist
  - jekyll-redirect-from


# Set which comment system to use
comments:
  provider: giscus

# You must install giscus github app before use.(https://github.com/apps/giscus)
# Make sure all variables are set properly. Check below link for detail.
# https://giscus.vercel.app/
giscus:
  repo:                "haade-administrator/haade.fr"
  repo-id:             "R_kgDOHxeeuA"
  category:            "Comments"
  category-id:         "DIC_kwDOHxeeuM4CTn1C"
  mapping:             "title"
  strict:              "1"
  reaction-enabled:    "1"
  emit-metadata:       "0"
  theme:               "light"
  position:            "top"
  loading:             "lazy"
  lang:                "fr"
  crossorigin:         "anonymous"

# Liste des catégories
collections:
  category:
    output: true
    en:
      output: true
      post:
        output: true
      shop:
        output: true
        brand:
          output: true
        protocol:
          output: true
      
    fr:
      output: true
      post:
        output: true
      shop:
        output: true
        marque:
          output: true
        protocole:
          output: true
  gallery:
    output: false
  products:
    output: true
    sort_by: date

defaults:
  - scope:
      path: "_posts/fr" 
      type: "posts"
    values:
      layout: "post"
      locale: fr_FR
      permalink: fr/blog/:title

  - scope:
      path: "_posts/en" 
      type: "posts"
    values:
      layout: "post"
      locale: en_GB
      permalink: en/blog/:title

  - scope:
      path: "_products/fr" 
    values:
      layout: "product"
      locale: fr_FR
      permalink: fr/produit/:title

  - scope:
      path: "_products/en" 
    values:
      layout: "product"
      locale: en_GB
      permalink: en/product/:title

  - scope:
      path: "_category/fr/post" 
    values:
      layout: "category"
      locale: fr_FR
      permalink: fr/categorie/:name


  - scope:
      path: "_category/en/post" 
    values:
      layout: "category"
      locale: en_GB
      permalink: en/category/:name

  - scope:
      path: "_category/fr/shop" 
    values:
      layout: "category"
      locale: fr_FR
      permalink: fr/categorie-produit/:name


  - scope:
      path: "_category/en/shop" 
    values:
      layout: "category"
      locale: en_GB
      permalink: en/category-product/:name



# Jekyll paginate v2 Pagination
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 6
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'
  # Optional, the default tag to use, omit to disable
  tag: ''
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: 'fr_FR'
 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

######################### end jekyll-paginate-v2 ###################################

# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:
  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: false
  
######################### end jekyll-autopages-v2 ###################################


# Other
# highlighter: rouge
# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable: true


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Vanilla back to top ("enabled" or "disabled")
# backtotop: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Cookie consent ("enabled" or "disabled")
cookie_consent: "disabled"

# countapi.xyz
countapi:
  namespace: # haade.fr
  key: # 97a74694-cc9d-43bb-9948-4d63fdccef94

# Sass
sass:
  sass_dir: _sass
  style: compressed

# compress link http://jch.penibelst.de/

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]


# jekyll picture tag

picture:
  disabled: false
  source: "assets/images"
  output: "assets/images/generated"
  suppress_warnings: true
  relative_url: true
  ignore_missing_images: true
  nomarkdown: false

# jekyll gist
gist:
  noscript: false

exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - .jekyll-cache
  - banner.js
  - node_modules
  - .vscode

# copy_to_dest plugins node_modules https://talk.jekyllrb.com/t/including-fontawesome-webfonts-from-node-modules/4486

