name: Build and deploy Jekyll H2ade Blog

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE.txt

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.0.2

      - name: Install and Build
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt dist-upgrade
          sudo apt install libvips imagemagick gvfs libvips-doc libvips-tools poppler-utils ghostscript apache2 -y
          node -v
          npm -v
          echo 'visu app list ufw'
          sudo ufw app list
          echo 'activation service Apache Secure'
          sudo ufw allow 'Apache Secure'
          echo 'redémarrage service ufw'
          sudo service ufw restart
          echo 'status de fonctionnement ufw'
          sudo service ufw status
          echo 'activation ufw'
          sudo ufw enable
          echo 'status apache pour ufw'
          sudo ufw status
          echo 'redémarrage Apache2'
          sudo service apache2 restart
          echo 'status Apache2'
          sudo service apache2 status
          echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
          echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
          echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          sudo gem install compass jekyll bundler
          sass -v
          bundle config set --local path 'vendor/bundle'
          bundle install
          bundle exec jekyll clean
          JEKYLL_ENV=production bundle exec jekyll build


      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }}
