name: Build and deploy Jekyll H2ade Blog

on:

  push:
    branches:
      - 'main'
#      - 'releases/**'
#      - '!releases/**-alpha'

#    tags:
#      - v1.*.*
      
  schedule:
  - cron: "0 2 * * *"

    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE.txt  

env:
  LANG: "fr_FR.UTF-8"
 
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:

      - name: Sleep for 30 seconds
        uses: whatnick/wait-action@master
        with:
          time: '30s'

      - name: fr_FR.UTF-8
        run: |
          sudo locale-gen fr_FR.UTF-8
          sudo update-locale LANG=fr_FR.UTF-8
  
      - name: date
        run: |
          date
    
      - name: Checkout 🛎️
        uses: actions/checkout@v3.3.0

      - name: Install and Build
        run:
          sudo apt-get -s upgrade | grep -P "\d\K upgraded" 
          sudo apt install libvips libvips-dev libvips-tools libvips-tools gvfs poppler-utils ghostscript -y
          locale
          node -v
          npm -v
          npm install
          npm run scrap
          echo aliexpress-domadoo scraper OK
          npm run build:js
          echo uglify js OK
          vips -v
          echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
          echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
          echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          sudo gem install compass jekyll bundler
          sass -v
          bundle config set --local path 'vendor/bundle'
          bundle install && bundle update
          JEKYLL_ENV=production bundle exec jekyll build


      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }}
